//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "st3bitReg.h"
#include "stOpRow.h"
#include "stTestIO.h"


#define OP_TABLE_LENG 12

class stOpTableHandle
{

private:
    
    stOpRow opTable[OP_TABLE_LENG];
    stTestIO parseOp;

public:
    
    int getTableData(char* sName, int iCount);
    void fillOpTable();
    char* getMnemonic();
    int getTotal();
    void incrementTotal(st3bitReg OpCode);
    int sumCycles();

};

